spelling: not...and...not
Signed-off-by: Josh Soref <2119212+jsoref@users.noreply.github.com>

diff --git a/mvnw b/mvnw
--- a/mvnw
+++ b/mvnw
@@ -72,7 +72,7 @@ set_java_home() {
     )" || :
 
     if [ ! -x "${JAVACMD-}" ] || [ ! -x "${JAVACCMD-}" ]; then
-      echo "The java/javac command does not exist in PATH nor is JAVA_HOME set, so mvnw cannot run." >&2
+      echo "The java/javac command does not exist in PATH and is JAVA_HOME not set, so mvnw cannot run." >&2
       return 1
     fi
   fi
